### ISSUE TITLE
Module causes app to crash when put in background

### ISSUE THREAD

**Issue by garrettlangley** [softgravity/titanium_flurry#1]

**Comment by dhcustom** [comment]
What OS? What version of the module? Which Titanium SDK are you using? It's working fine for me, as I'm actually using it to detect when users pause  my app. Is there any more details of how you are using it?

**Comment by garrettlangley** [comment]
iOS 4.3 running on the Simulator (on iPhone 4 the problem also occurs)
Ti SDK 1.7.2

Also have the StoreKit and UrbanAirship modules. Without sg.flurry, everything is fine. When I include sg.flurry and only the following code:
var flurry = require('sg.flurry');
flurry.secureTransport(true);
flurry.logUncaughtExceptions(true); 
flurry.startSession('my key was here'); 

The app crashes on pause. In XCode, it goes to a thread with the following: 
[FlurryAnalytics stopBackgroundTask]
[FlurrySession sendSessionsToServerForSessionPause]

And shows this error:
"Program received signal: EXC_BAD_ACCESS"

Thanks in advance for the help

**Comment by dhcustom** [comment]
It seems like a flurry issue, not too much I can control. Because the error says this "[FlurrySession sendSessionsToServerForSessionPause]" I believe it has something to do with trying to send the events when the app is paused, although that should be off by default.

Try using flurry.reportOnPause(false). Also don't use secureTransport and don't logUncaughtException. Especially secureTransport, it's a new function introduced in 3.0.0 which might not work too well. May I suggest also trying the older version of the module? v1.0?

Let me know if it helps!

**Comment by garrettlangley** [comment]
adding flurry.reportOnPause(false) fixed the problem. i also turned off, per your suggestion, logUncaught and secureTransport.

thanks for the help!

**Comment by dhcustom** [comment]
since reportOnPause worked, I would suggest at least turning back on logUncaught, it's a great tool when your app goes live! Glad to be helpful.

**Comment by garrettlangley** [comment]
thanks again for the help!
