### ISSUE TITLE
Titanium 1.8+ ?

### ISSUE THREAD

**Issue by svickers** [softgravity/titanium_flurry#4]
Using the files from the dist folder I'm having trouble getting this to work with 1.8.0.1 for android, says the version has to be above 2.  Any plans to update?

**Comment by dhcustom** [comment]
iOS? Android? Error message?
The iOS version was tested with 1.8.0.1 in the Simulator with iOS 5.0

**Comment by svickers** [comment]
Android:

[DEBUG] module_id = sg.flurry
[ERROR] The 'apiversion' for 'sg.flurry' in the module manifest is not a valid value.  Please use a version of the module that has an 'apiversion' value of 2 or greater set in it's manifest file

**Comment by wkchen5872** [comment]
iOS worked fine

Android 1.1 compiler error message

symbol  : class AndroidflurryBootstrap
location: package sg.flurry
        runtime.addExternalModule("sg.flurry", sg.flurry.AndroidflurryBootstrap.class);
                                                        ^
1 error

I refer to  Android Module Porting Guide for 1.8.0.1(https://wiki.appcelerator.org/display/guides/Android+Module+Porting+Guide+for+1.8.0.1) 

I follow "Manifest changes" "Build changes" and "Specific changes" 

Error message
    [javac] /Users/kisskie/workspace/TiModule/titanium_flurry/android/build/generated/java/sg/flurry/AndroidflurryModulePrototype.java:165: inconvertible types
    [javac] found   : java.lang.Object
    [javac] required: byte
    [javac]         arg0 = (byte) TypeConverter.jsObjectToJavaObject(args[0], thisObj) ;
    [javac]                                                         ^
    [javac] Note: /Users/kisskie/workspace/TiModule/titanium_flurry/android/build/generated/java/sg/flurry/AndroidflurryModulePrototype.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
/Users/kisskie/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/module/android/build.xml:156: Compile failed; see the compiler error output for details

**Comment by dhcustom** [comment]
Sorry, but the the android version is not built for 1.8.0+ at the current moment. Taking a quick look at the guide, I think most of the code needs to be re-written since it uses lots of context everywhere. I will get to this when I get a chance. It seems rather straight forward though, I hope someone else can take a look at this and provide and update in the meantime. :)

**Comment by tokmakoff** [comment]
It seems that the Rhino type converter cannot handle Kroll methods that have a byte argument.  Two work arounds are to either disable the rhino bindings task (generate.rhino.bindings) in the android/module/build.xml (if you only want v8), or to change the kroll method setGender() to argument type int instead of byte.  Then the build works OK.

In terms of the context mods, I just added a line to the constructor and used it throughout..

``` java
public AndroidflurryModule() {
        super();
        context = TiApplication.getInstance().getApplicationContext();
    }
```

**Comment by dhcustom** [comment]
Fixed now.
