### ISSUE TITLE
Min SDK 1.8

### ISSUE THREAD

**Issue by marcwickens** [softgravity/titanium_flurry#9]
Just wondering if it's possible to use this on a 1.7.3 project? My app breaks in 1.8 so don't really want to update it if it's not necessary.

**Comment by dhcustom** [comment]
You have 2 options.
1) Use the v1.1 which was built for titanium 1.6.2 which should work in 1.7.3.
2) Fork the code, change the manifest file to min sdk 1.7.3 and build it with 1.7.3 for yourself.

**Comment by benbahrenburg** [comment]
I've got a beta of this running on 1.8 in this fork here https://github.com/benbahrenburg/titanium_flurry/tree/master/android

Once tested will send a pull request.

**Comment by dhcustom** [comment]
I think the original poster was referring to the iOS version, since the Android version does not work right now in 1.8. 

I have looked over the code for 1.8 in Android and have a few suggestions:

1) the *.class files don't need to be in the repository
2) set minsdk to 1.8.0.1 or 1.8.1 so that any user who require 1.8.x can use the module
3) leave the setGender function and the constants as is because it mimics the flurrly implementation and allows users to refer to their documentation to figure out how to use the module (http://support.flurry.com/sdkdocs/android/classcom_1_1flurry_1_1android_1_1_flurry_agent.html#a0c85f00f7424c33906b1d7f15ea10b8e)
4) maybe add setUseHttps (boolean useHttps) and setCaptureUncaughtExceptions (boolean isEnabled) functions as well

Other than that awesome! I'm glad only need to change the way context is referenced to fix it.

**Comment by benbahrenburg** [comment]
I ran into some issues with using byte as consistent and switched over to int instead. Will look into the rest fore a pull request.

**Comment by marcwickens** [comment]
Thanks folks - I am looking to update to the latest Flurry SDK on iOS, but I am trying to avoid needing to update my project to Appcelerator 1.8 as that breaks a lot of stuff, and I don't really have the time to fix all those problems. I will try building the 1.1 with the newer Flurry SDK and see where that gets me.

Thanks again.

**Comment by dhcustom** [comment]
Marc:
If you need the latest Flurry SDK I actually suggest you work backward. Pull the latest code from github, change the titanium sdk in the titanium.xcconfig and manifest file to 1.7.3 then run "titanium build" or "titanium run" to generate your own custom build.

Ben:
Odd, not sure why that would be. What kinda or issues were you getting, maybe I can assist.

**Comment by dhcustom** [comment]
it's been fixed now. Use latest 3.0.2.GA
